### ISSUE TITLE
Really? Terraform and not CloudFormation?

### ISSUE THREAD

**Issue by nikolay** [awslabs/lambda-runcommand-configuration-management#5]

**Comment by seajoshc** [comment]
HashiCorp is a great AWS APN partner and Terraform is a fantastic tool just like CloudFormation!  At the time, CFN was missing support for some components we were using.  This is no longer the case and we'll consider creating a CFN template for this example.

**Comment by nikolay** [comment]
@irlrobot You guys need to be more vocal internally as those of us who chose to stick with AWS best practices have to suffer for being loyal! Yes, CloudFormation lags severely behind, and although I understand most of the reasons, there's no excuse as HashiCorp is a small shop, but delivers tons more!

It's also not in your best interest to push people into tools that make people leave your cloud without much effort - just saying!

When you release a feature, it needs to be released  **simultaneously** to SDKs, AWS CLI, and CloudFormation! So, please, give heat to your coworkers. Please!

I think CloudFormation should be open-sourced - there are many alternatives now - Terraform, Fugue, SparkleFormation, etc. - you can't survive at this crawling speed!

**Comment by nikolay** [comment]
@irlrobot So, you gave up. It's disloyal to support Terraform (i.e., HashiCorp, which is also a competitor) and Ansible (by Red Hat, i.e., somewhat a competitor), and not your employer's toolchain, which is a lot more active since 2016 when I opened the issue!
